### PR TITLE
updated banner & logo & minor place/time places on home page

### PR DESCRIPTION
**Pull request by jiangxuann**
but the banner is the wrong size currently this remains to be fixed

### CODE REVIEW

**Comment by katelynsyu** [comment]
Hello. so soft launch of HOTH is gonna be this week and we cant have the website with a bunch of location and date TBDs esp on the first page, so what you're gonna do is revert the banner back to hoth 9 banner and keep all your other changes. then we're gonna merge. so if you could do that and request me asap so we can get this website up that would be amazing. thank you!

**Review by katelynsyu — CHANGES_REQUESTED** [review]
Also could you delete the files: 
- hothX-web-banner.png
- hoth9-logo.svg
- web-banner.svg
- fb_logo.svg

Thanks! We're almost done with the pR!

**Review by katelynsyu — APPROVED** [review]
lgtm! Thank you for getting this done on such short notice!

**Review by katelynsyu — APPROVED** [review]
lgtm! Thank you for getting this done on such short notice!

**Review by maggieelli — APPROVED** [review]
looks good!

**Pull request merged**
