### PR TITLE
Added Sticky Nav Menu

### PR DESCRIPTION
**Pull request by SubramaniamSatyen**
The text can be customized. Spent a bit of time looking into getting the current section to be highlighted - I believe it's doable with the useRef() hook. Otherwise I believe changes add intended functionality

### CODE REVIEW

**Review by katelynsyu — CHANGES_REQUESTED** [review]
can we play around with using primary and secondary colors for the buttons on the nav menu to offset all the dark text on the page? also is it possible to push the nav bar text down so when we're at the top of the page the nav bar text is aligned with the "workshop" title?

**Review by katelynsyu — CHANGES_REQUESTED** [review]
Also it doesn't seem like you're using window.js, so maybe deleting the file is best? For future reference, you can use theme.breakpoints if you want to edit how a component looks based on how narrow a window is :)

**Comment by SubramaniamSatyen** [comment]
I've gone ahead and added some extra styling and removed the window page. Feel free to let me know if anything still needs to be changed whenever you get the chance.

**Comment by katelynsyu** [comment]
YAY!!! I think the functionality is perfect!!! Now we just have to work on editing how it looks. Is it possible to get rid of the indent and the bullet point for the sidebar? Also can we add a faint line on the right side of the sidebar to show a differentiation between the navbar and the rest of the screen? 

Honestly, I really don't know what would look better, so I'm just spit balling ideas. Play around with it and if you don't like my ideas, feel free to change them :). Thanks!!

**Comment by SubramaniamSatyen** [comment]
Added a bit more styling, but let me know feel free to let me know if it still looks off or any additional thoughts

**Review by jakobreinwald — APPROVED** [review]
LGTM everything looks great, thanks for all the work back and forth with us. :)

**Review by katelynsyu — APPROVED** [review]
LGTM!

**Pull request merged**
