### PR TITLE
Changed remaining "Hack off" to "Hack on"

### PR DESCRIPTION
**Pull request by jodymlin**
Removed all remaining instances of "Hack Off" in the site metadata and changed it to "Hack On"

### CODE REVIEW

**Review by khxia — APPROVED** [review]
yeet

**Comment by TimothyGu** [comment]
One more:

https://github.com/uclaacm/hoth.uclaacm.com/blob/d60e4b929f0db77459f10dd69a2119f639be673d/package.json#L4

**Comment by khxia** [comment]
Oops, will fix now

**Comment by jodymlin** [comment]
Oh my god I swear if we go virtual and we have to change it back to "off" I'm going to throw hands 😭 

But also ty for the catch I must've filtered out the file in VSCode on accident

**Pull request merged**
