### PR TITLE
Update Event Schedules 

### PR DESCRIPTION
**Pull request by katelynsyu**
update time and duration of Meme competition, updated descriptions for events, update duration of Jedi Allyship space.

### CODE REVIEW

**Review by jodymlin — APPROVED** [review]
How did you manage to make the blurbs funnier than they were before LMAO

Love it 😍

**Review by EinarBalan — COMMENTED** [review]
i will defer to christina for the content but not sure if this was there before but i am having a very odd visual glitch where the date from each section kinda travels with you?? idk kinda hard to explain but here are some screenshots
Screen Shot 2022-02-14 at 6 23 04 PM
Screen Shot 2022-02-14 at 6 23 00 PM
Screen Shot 2022-02-14 at 6 22 55 PM
Screen Shot 2022-02-14 at 6 22 52 PM
Screen Shot 2022-02-14 at 6 22 46 PM

**Comment by EinarBalan** [comment]
^^ or wait is that intentional

**Review by EinarBalan — APPROVED** [review]

**Review by christinatong01 — APPROVED** [review]
lgtm! thank you :)

**Pull request merged**
